import { useEffect, useState } from "react";
import { api, Domain, domainRoles, Member, systemRoles, User } from "./api";
import { Dialog, message } from "./ui";

export function Access({ onError }: { onError: (value: string) => void }) {
  const [tab, setTab] = useState<"users" | "domains">("domains"); const [users, setUsers] = useState<User[]>([]); const [domains, setDomains] = useState<Domain[]>([]);
  const [selectedDomain, setSelectedDomain] = useState(""); const [members, setMembers] = useState<Member[]>([]);
  const [userOpen, setUserOpen] = useState(false); const [domainOpen, setDomainOpen] = useState(false);
  const [grantUser, setGrantUser] = useState(""); const [grantRole, setGrantRole] = useState("reader"); const [busy, setBusy] = useState(false); const [revoke, setRevoke] = useState<Member | null>(null);
  const shared = domains.filter((domain) => domain.classification === "restricted" && !domain.code.startsWith("private-"));
  const refresh = () => Promise.all([api<User[]>("/admin/users"), api<Domain[]>("/domains")]).then(([nextUsers, nextDomains]) => { setUsers(nextUsers); setDomains(nextDomains); });
  const refreshMembers = () => selectedDomain ? api<Member[]>(`/admin/domains/${selectedDomain}/members`).then(setMembers).catch((cause) => onError(message(cause))) : Promise.resolve(setMembers([]));
  useEffect(() => { refresh().catch((cause) => onError(message(cause))); }, []);
  useEffect(() => { refreshMembers(); }, [selectedDomain]);
  return <main className="page"><header className="page-heading"><div><h1>Управление доступом</h1><p className="muted">Системные пользователи и доступ к закрытым документам</p></div></header><nav className="tabs" aria-label="Управление доступом"><button className={tab === "domains" ? "tab-active" : "quiet"} onClick={() => setTab("domains")}>Пространства доступа</button><button className={tab === "users" ? "tab-active" : "quiet"} onClick={() => setTab("users")}>Пользователи</button></nav>
    {tab === "users" && <><div className="section-heading"><div><h2>Пользователи</h2><p className="muted">Системная роль определяет действия в приложении. Доступ к закрытым документам задаётся отдельно.</p></div><button onClick={() => setUserOpen(true)}>Новый пользователь</button></div><div className="panel compact">{users.map((user) => <div className="member-row" key={user.id}><strong>{user.email}</strong><span>{systemRoles[user.role]}</span></div>)}</div></>}
    {tab === "domains" && <><div className="section-heading"><div><h2>Общие пространства</h2><p className="muted">Участники пространства получают доступ к его закрытым документам.</p></div><button onClick={() => setDomainOpen(true)}>Создать пространство</button></div>{shared.length ? <div className="access-layout"><div className="panel domain-list">{shared.map((domain) => <button key={domain.id} className={selectedDomain === domain.id ? "selected" : "quiet"} onClick={() => setSelectedDomain(domain.id)}>{domain.title}<small>{domain.code}</small></button>)}</div>{selectedDomain ? <div className="panel"><h2>{shared.find((domain) => domain.id === selectedDomain)?.title}</h2><h3>Участники</h3>{members.length ? members.map((member) => <div className="member-row" key={member.id}><strong>{member.email}</strong><select aria-label={`Роль ${member.email}`} value={member.role} disabled={busy} onChange={async (event) => { setBusy(true); try { await api(`/admin/domains/${selectedDomain}/members/${member.id}`, { method: "PUT", body: JSON.stringify({ role: event.target.value }) }); await refreshMembers(); } catch (cause) { onError(message(cause)); } finally { setBusy(false); } }}>{Object.entries(domainRoles).map(([key, label]) => <option value={key} key={key}>{label}</option>)}</select><button className="quiet danger-text" onClick={() => setRevoke(member)}>Удалить доступ</button></div>) : <p className="muted">Участников пока нет.</p>}<h3>Добавить участника</h3><div className="toolbar"><label>Пользователь<select value={grantUser} onChange={(event) => setGrantUser(event.target.value)}><option value="">Выберите пользователя</option>{users.filter((user) => !members.some((member) => member.id === user.id)).map((user) => <option key={user.id} value={user.id}>{user.email}</option>)}</select></label><label>Роль в пространстве<select value={grantRole} onChange={(event) => setGrantRole(event.target.value)}>{Object.entries(domainRoles).map(([key, label]) => <option key={key} value={key}>{label}</option>)}</select></label><button disabled={!grantUser || busy} onClick={async () => { setBusy(true); try { await api(`/admin/domains/${selectedDomain}/members/${grantUser}`, { method: "PUT", body: JSON.stringify({ role: grantRole }) }); setGrantUser(""); await refreshMembers(); } catch (cause) { onError(message(cause)); } finally { setBusy(false); } }}>Добавить</button></div></div> : <div className="empty">Выберите пространство, чтобы увидеть участников.</div>}</div> : <div className="empty"><h3>Общих пространств пока нет</h3><p>Создайте пространство, затем добавьте участников и загружайте туда документы.</p><button onClick={() => setDomainOpen(true)}>Создать пространство</button></div>}</>}
    {userOpen && <NewUser onClose={() => setUserOpen(false)} onDone={refresh} onError={onError} />}
    {domainOpen && <NewDomain onClose={() => setDomainOpen(false)} onDone={async () => { await refresh(); }} onError={onError} />}
    {revoke && <Dialog title="Удалить доступ?" onClose={() => setRevoke(null)}><p>{revoke.email} потеряет доступ к документам пространства «{shared.find((item) => item.id === selectedDomain)?.title}».</p><div className="form-actions"><button className="secondary" onClick={() => setRevoke(null)}>Отмена</button><button className="danger" disabled={busy} onClick={async () => { setBusy(true); try { await api(`/admin/domains/${selectedDomain}/members/${revoke.id}`, { method: "DELETE" }); setRevoke(null); await refreshMembers(); } catch (cause) { onError(message(cause)); } finally { setBusy(false); } }}>Удалить доступ</button></div></Dialog>}
  </main>;
}

function NewUser({ onClose, onDone, onError }: { onClose: () => void; onDone: () => Promise<unknown>; onError: (value: string) => void }) {
  const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [role, setRole] = useState("reader"); const [busy, setBusy] = useState(false);
  return <Dialog title="Новый пользователь" onClose={onClose}><form className="form" autoComplete="off" onSubmit={async (event) => { event.preventDefault(); setBusy(true); try { await api("/admin/users", { method: "POST", body: JSON.stringify({ email, password, role }) }); await onDone(); onClose(); } catch (cause) { onError(message(cause)); } finally { setBusy(false); } }}><label>Почта нового пользователя<input type="email" name="new-user-email" autoComplete="off" value={email} onChange={(event) => setEmail(event.target.value)} required /></label><label>Временный пароль<input type="password" name="new-user-password" autoComplete="new-password" minLength={12} value={password} onChange={(event) => setPassword(event.target.value)} required /></label><label>Системная роль<select value={role} onChange={(event) => setRole(event.target.value)}>{Object.entries(systemRoles).map(([key, label]) => <option key={key} value={key}>{label}</option>)}</select></label><p className="hint">Роль в конкретном пространстве назначается отдельно.</p><div className="form-actions"><button type="button" className="secondary" onClick={onClose}>Отмена</button><button disabled={busy}>{busy ? "Создаём…" : "Создать пользователя"}</button></div></form></Dialog>;
}

function NewDomain({ onClose, onDone, onError }: { onClose: () => void; onDone: () => Promise<unknown>; onError: (value: string) => void }) {
  const [code, setCode] = useState(""); const [title, setTitle] = useState(""); const [busy, setBusy] = useState(false);
  return <Dialog title="Новое пространство доступа" onClose={onClose}><form className="form" onSubmit={async (event) => { event.preventDefault(); setBusy(true); try { await api("/admin/domains", { method: "POST", body: JSON.stringify({ code, title }) }); await onDone(); onClose(); } catch (cause) { onError(message(cause)); } finally { setBusy(false); } }}><label>Название пространства<input value={title} minLength={2} maxLength={120} onChange={(event) => setTitle(event.target.value)} required /></label><label>Технический код<input value={code} pattern="[a-z0-9][a-z0-9_-]{1,63}" onChange={(event) => setCode(event.target.value)} placeholder="Например, metallurgy" required /></label><p className="hint">Код используют для идентификации пространства. Создатель получает роль руководителя.</p><div className="form-actions"><button type="button" className="secondary" onClick={onClose}>Отмена</button><button disabled={busy}>{busy ? "Создаём…" : "Создать пространство"}</button></div></form></Dialog>;
}

