import { useEffect, useRef, useState } from "react";
import { api, Capabilities, dateTime, DocumentItem, Domain, downloadPackage, params, User } from "./api";
import { Dialog, message } from "./ui";

export function Library({ user, onError }: { user: User; onError: (value: string) => void }) {
  const [docs, setDocs] = useState<DocumentItem[]>([]); const [domains, setDomains] = useState<Domain[]>([]);
  const [capabilities, setCapabilities] = useState<Capabilities | null>(null);
  const [search, setSearch] = useState(""); const [classification, setClassification] = useState(""); const [domainId, setDomainId] = useState(""); const [page, setPage] = useState(0);
  const [loading, setLoading] = useState(true); const [uploadOpen, setUploadOpen] = useState(false); const [importOpen, setImportOpen] = useState(false);
  const [selected, setSelected] = useState<DocumentItem | null>(null); const [acting, setActing] = useState(""); const request = useRef(0); const limit = 25;
  const refresh = () => { const token = ++request.current; setLoading(true); api<DocumentItem[]>(`/documents${params({ q: search, classification, domain_id: domainId, offset: page * limit, limit })}`).then((result) => { if (token === request.current) setDocs(result); }).catch((cause) => { if (token === request.current) onError(message(cause)); }).finally(() => { if (token === request.current) setLoading(false); }); };
  useEffect(() => { api<Domain[]>("/domains").then(setDomains).catch((cause) => onError(message(cause))); api<Capabilities>("/capabilities").then(setCapabilities).catch((cause) => onError(message(cause))); }, []);
  useEffect(refresh, [search, classification, domainId, page]);
  const act = async (id: string, action: "analyze" | "export") => { setActing(`${action}:${id}`); try { if (action === "analyze") { const result = await api<{ described_pages: number }>(`/documents/${id}/analyze-images`, { method: "POST" }); onError(`Анализ завершён. Описано страниц: ${result.described_pages}.`); } else await downloadPackage(id); } catch (cause) { onError(message(cause)); } finally { setActing(""); } };
  return <main className="page"><header className="page-heading"><div><h1>Библиотека</h1><p className="muted">Доступные документы для поиска и исследования</p></div><div className="header-actions">{user.role === "admin" && <button className="secondary" onClick={() => setImportOpen(true)}>Импорт ZIP</button>}{user.role !== "reader" && <button onClick={() => setUploadOpen(true)}>Загрузить документ</button>}</div></header><p className="hint library-hint">Загрузка добавляет документ в библиотеку. Исследование ищет среди доступных источников; документ не прикрепляется к нему вручную.</p>
    <div className="toolbar"><label>Поиск<input type="search" value={search} placeholder="Название документа" onChange={(event) => { setSearch(event.target.value); setPage(0); }} /></label><label>Доступ<select value={classification} onChange={(event) => { setClassification(event.target.value); setPage(0); }}><option value="">Все документы</option><option value="public">Открытые</option><option value="restricted">Закрытые</option></select></label><label>Пространство<select value={domainId} onChange={(event) => { setDomainId(event.target.value); setPage(0); }}><option value="">Все доступные</option>{domains.map((domain) => <option key={domain.id} value={domain.id}>{domain.title}</option>)}</select></label></div>
    {loading ? <p role="status">Загружаем документы…</p> : docs.length ? <div className="document-list">{docs.map((doc) => <div className="document-row" key={doc.id}><button className="document-title" onClick={() => setSelected(doc)}>{doc.title}</button><div className="document-meta"><span className="badge">{doc.classification === "public" ? "Открытый" : "Закрытый"}</span><span>{doc.domain_title || "Без пространства"}</span><span>{dateTime(doc.created_at)}</span></div></div>)}</div> : <div className="empty"><h2>Документов нет</h2><p>Поменяйте фильтр или загрузите первый документ.</p></div>}
    <div className="pagination"><button className="secondary" disabled={page === 0 || loading} onClick={() => setPage(page - 1)}>Назад</button><span>Страница {page + 1}</span><button className="secondary" disabled={docs.length < limit || loading} onClick={() => setPage(page + 1)}>Далее</button></div>
    {selected && <Dialog title={selected.title} onClose={() => setSelected(null)}><div className="detail-list"><p><strong>Доступ:</strong> {selected.classification === "public" ? "Открытый" : "Закрытый"}</p><p><strong>Пространство:</strong> {selected.domain_title || "Без пространства"}</p><p><strong>Добавлен:</strong> {dateTime(selected.created_at)}</p></div><div className="form-actions wrap"><a className="button-link secondary" href={`#/document/${selected.id}`}>Открыть документ</a>{selected.can_analyze && <button disabled={!!acting} onClick={() => act(selected.id, "analyze")}>{acting === `analyze:${selected.id}` ? "Анализируем…" : "Проанализировать схемы"}</button>}{selected.can_export && <button className="secondary" disabled={!!acting} onClick={() => act(selected.id, "export")}>Экспортировать пакет</button>}</div></Dialog>}
    {uploadOpen && <UploadDialog domains={domains} maxBytes={capabilities?.max_document_bytes} onClose={() => setUploadOpen(false)} onDone={refresh} onError={onError} />}
    {importOpen && <ImportDialog onClose={() => setImportOpen(false)} onDone={refresh} onError={onError} />}
  </main>;
}

function UploadDialog({ domains, maxBytes, onClose, onDone, onError }: { domains: Domain[]; maxBytes?: number; onClose: () => void; onDone: () => void; onError: (value: string) => void }) {
  const [file, setFile] = useState<File | null>(null); const [domainId, setDomainId] = useState(""); const [busy, setBusy] = useState(false);
  const tooLarge = !!file && !!maxBytes && file.size > maxBytes;
  return <Dialog title="Загрузить документ" onClose={onClose}><form className="form" onSubmit={async (event) => { event.preventDefault(); if (!file || tooLarge) return; setBusy(true); try { const data = new FormData(); data.append("file", file); await api(`/documents${params({ classification: "restricted", domain_id: domainId })}`, { method: "POST", body: data }); onDone(); onClose(); } catch (cause) { onError(message(cause)); } finally { setBusy(false); } }}><label>Файл PDF, HTML или TXT<input type="file" accept=".pdf,.html,.txt" onChange={(event) => setFile(event.target.files?.[0] || null)} required /></label><label>Пространство доступа<select value={domainId} onChange={(event) => setDomainId(event.target.value)}><option value="">Личное закрытое пространство</option>{domains.filter((domain) => domain.classification === "restricted" && ["researcher", "manager"].includes(domain.role || "") && !domain.code.startsWith("private-")).map((domain) => <option key={domain.id} value={domain.id}>{domain.title}</option>)}</select></label><p className="hint">{domainId ? "Документ смогут использовать участники выбранного пространства с соответствующими правами." : "Документ будет доступен только вам."}{maxBytes ? ` Максимальный размер: ${Math.round(maxBytes / 1024 / 1024)} МБ.` : ""}</p>{tooLarge && <p className="error" role="alert">Файл превышает допустимый размер.</p>}<div className="form-actions"><button className="secondary" type="button" onClick={onClose}>Отмена</button><button disabled={!file || tooLarge || busy}>{busy ? "Загружаем и обрабатываем…" : "Загрузить"}</button></div></form></Dialog>;
}

function ImportDialog({ onClose, onDone, onError }: { onClose: () => void; onDone: () => void; onError: (value: string) => void }) {
  const [file, setFile] = useState<File | null>(null); const [busy, setBusy] = useState(false);
  return <Dialog title="Импорт пакета источников" onClose={onClose}><form className="form" onSubmit={async (event) => { event.preventDefault(); if (!file) return; setBusy(true); try { const data = new FormData(); data.append("file", file); await api("/packages/import", { method: "POST", body: data }); onDone(); onClose(); } catch (cause) { onError(message(cause)); } finally { setBusy(false); } }}><p className="hint">ZIP-пакет добавит открытые источники в библиотеку.</p><label>ZIP-пакет<input type="file" accept=".zip" required onChange={(event) => setFile(event.target.files?.[0] || null)} /></label><div className="form-actions"><button type="button" className="secondary" onClick={onClose}>Отмена</button><button disabled={!file || busy}>{busy ? "Импортируем…" : "Импортировать"}</button></div></form></Dialog>;
}

